image: node:latest
# To use Remote Caching, uncomment the next lines and follow the steps below.
# variables:
#   TURBO_TOKEN: $TURBO_TOKEN
#   TURBO_TEAM: $TURBO_TEAM
stages:
  - build
  - lint-server
  - lint-client
  - test
  - test:e2e
build:
  stage: build
  image: node:latest
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm run build
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

Lint-Client:
  stage: lint-client
  image: node:latest
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm run web-client-lint
  rules:
    - changes:
        - apps/web-client/*

Lint-Server:
  stage: lint-server
  image: node:latest
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm run nest-server-lint
  rules:
    - changes:
        - apps/nest-server/*

Test-e2e:
  stage: test:e2e
  image: node:latest
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm run backendtest:e2e
  rules:
    - changes:
        - apps/nest-server/*
